project:
  type: book
filters:
   - include-code-files
book:
  title: "Java,Typescript to C#"
  author: "Atilla Özgür"
  date: "1/8/2026"
  chapters:
    - index.qmd
    - course-content/intro.qmd
    - course-content/installation.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



